### ISSUE TITLE
404 doesn't work

### ISSUE THREAD

**Issue by savioxavier** [gominima/website#6]
I'm not sure why, but the 404 page (rendered by `[...all].vue`) doesn't work?

![image](https://user-images.githubusercontent.com/38729705/152933386-eaa9802e-0bbe-4ff2-aef2-8913c02b8bac.png)

It's the same with the latest commit of #5 too, maybe it's a Netlify config error?

**Comment by apoorvcodes** [comment]
Seem to work for me

**Comment by savioxavier** [comment]
That's pretty weird, what about you @megatank58?

**Comment by booleanrecep** [comment]
In your URL there is no hash( '/#' ). I think the router is configured with the hash router and its good to use it to get rid of reload issues. There must be a workaround for issue you specified. So for now if you use hash in URL you ll be able to see expeccted result

**Comment by savioxavier** [comment]
Works with the hash now (`/#`). Should probably find a fix for this, if that's possible, because we can't have that happening.

**Comment by apoorvcodes** [comment]
@booleanrecep Thanks for specifying the issue

**Comment by megatank58** [comment]
This should be fixed with a simple `netlify.toml`. Hash router will be removed with #5 soon and replaced with a normal router and [netlify redirects](https://router.vuejs.org/guide/essentials/history-mode.html#netlify)
